- Changed url to ssl_url in the examples
transloadit/java-sdk pull request #41
Opened 2021-04-13 20:51 UTC by cdr-chakotay

- Added MultiStepProcessing example and its Ressource files.
- MulitStepProcessing example also uses JSONObject to build AssemblyInstructions
- Added rootProject as dependency to example project in replacement of com.transloadit.sdk from JCenter
- closes #38

2021-04-14 20:25 UTC, Acconut requested changes
Very impressive work! I left a few comments, but please do not be discouraged by them :D

2021-04-14 20:25 UTC, Acconut commented on examples/build.gradle
> +    compile project(':')
The comment a few lines below, mentions `compile rootProject`. Not sure if we should use this instead since it is a bit more descriptive instead of `project(':')`. Furthermore, please remove the comment down below since we are not referencing the root project by default.

2021-04-14 20:25 UTC, Acconut commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +        assembly.addFile(new File(MultiStepProcessing.class.getResource("/dutch-anthem.mp3").getFile()),"a1");
Do we need attribution for the Dutch and German anthem? Probably not, right?

2021-04-14 20:25 UTC, Acconut commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +        assembly.addFile(new File(MultiStepProcessing.class.getResource("/german-anthem-0.mp3").getFile()),"a2");
A more descriptive field name like `file_1` instead of `a1` would be helpful. Brevity is nice but expressiveness is  nicer :D

2021-04-14 20:25 UTC, Acconut commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +                System.exit(0);
Is the system exit necessary here (i.e. will the process not stop without this forceful exit)? If possible, calls to `System.exit` should be avoided and instead the process should end "naturally"

2021-04-14 20:25 UTC, Acconut commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +        //Add Files and define Field name
Brief comment on the code style: Please use a space after beginning a comment with `//` and please use a space after a comma in a function call: `foo(a, b)`

I think Intellij should have an option to automatically format it, so you do not have to do it manually.

2021-04-14 21:23 UTC, cdr-chakotay commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +        assembly.addFile(new File(MultiStepProcessing.class.getResource("/dutch-anthem.mp3").getFile()),"a1");
Honestly i pulled them from the Demos on [transloadit.com](https://transloadit.com/demos/audio-encoding/concatenate-two-audio-files/).
Maybe we should asked the guy who made the demos,

2021-04-14 21:26 UTC, cdr-chakotay commented on examples/build.gradle
> +    compile project(':')
I'd like to address this again in another PR in which i will overhaul the Gradle files.
We should use implementation instead of compile (deprecated) anyways.

2021-04-14 21:28 UTC, cdr-chakotay commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +                System.exit(0);
In my case the process ran forever, but i will double check again .

2021-04-19 22:45 UTC, Acconut commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +        assembly.addFile(new File(MultiStepProcessing.class.getResource("/dutch-anthem.mp3").getFile()),"a1");
@kvz Can we use the Dutch and German anthem in this repository without specific attribution? We thought of using them since we already use them in the demos on transloadit.com but wanted to be sure with the correct licensing.

2021-04-19 22:46 UTC, merged

2021-04-19 22:47 UTC, Acconut commented
Congrats on your first merged PR :tada:

2021-04-20 07:09 UTC, kvz commented on examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java
> +        assembly.addFile(new File(MultiStepProcessing.class.getResource("/dutch-anthem.mp3").getFile()),"a1");
I am unsure what the origin is of these files. But they are small snippets, only 1 minute. I don't think an athem can be copyrighted, and by listening they appear to be midi-composed, so there isn't an orchestra to pay for the execution either at least. I think the risk will be acceptable, and if we get a takedown request, we'll either add the attribution or take them down at that time. If we want to be 100% safe tho, we can also use the track that we paid money for and rights of which are ours, or use different public tracks and add licensing info.

If you add these songs to the sdk repo, i could imagine that could be seen as redistributing/packaging. Use in demos are more easy to take down without many revisions and installs out there.