Handle RATE_LIMIT_REACHED errors
transloadit/java-sdk pull request #57
Opened 2021-05-15 14:41 UTC by cdr-chakotay

Progress so far:

- Added a retry() method to Request.class
- retry() method gets called if a post request's parameter list is not empty, a peek to the response body shows the error-code 413 and retries are left.
- Not implemented: Dynamic number of retries (defaults to 5) => Maybe implement this with Transloadit instance or provide a setter method.
- Problems with Junit tests and empty parameters lists are bypassed with the parameter list check, this should be discussed further

2021-05-15 21:21 UTC, Acconut requested changes
Amazing work! I left a few comments. Also, would it be possible to add a unit test for this?

2021-05-15 21:21 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Assembly.java
> +        this.retryAttempts = retryAttempts;
Do you think it would be helpful if this was a option in the `Transloadit` class, so it applies to all Assembly instances?

2021-05-15 21:21 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Assembly.java
> +            request.setRetryAttemptsLeft(retryAttempts);
Do you know if we also need a modification in the AsyncAssembly class? Or is this not necessary because the the inheritance?

2021-05-15 21:21 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Request.java
> +import okhttp3.*;
Do the linter not disagree here? :D (I personally don´t mind the star)

2021-05-15 21:21 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Request.java
> +                if (json.has("http_code") && json.get("http_code").toString().equals("413") && retryAttemptsLeft > 0) {
If you only want to access the HTTP response code, you do not have to parse the body at all. You can simply use the `Response#status` method: https://github.com/transloadit/java-sdk/blob/master/src/main/java/com/transloadit/sdk/response/Response.java#L36

(although it's still necessary to parse it for the retryIn value).

2021-05-15 21:21 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Request.java
> +    public void setRetryAttemptsLeft(int retryAttemptsLeft) {
Can this method be package-private instead of public?

2021-05-15 22:31 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/Assembly.java
> +        this.retryAttempts = retryAttempts;
I thought about it. 
It would be easier to have this in the Transloadit class as it would be uniform and I could hand over the values already in the constructor of the request.
In this case we should also discuss what the default value should be for retries. 0 or some small number like 5.

Do you want to keep the possibility to adjust the retries directly in each assembly? This could be confusing in production as the values would overwrite each other.


What do you think ?

2021-05-15 22:33 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/Request.java
> +import okhttp3.*;
... yes :D. 
IntelliJ is likely to replace multiple imports with a star. I am quite uncertain what I prefer at this pointed time.

2021-05-15 22:34 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/Request.java
> +                if (json.has("http_code") && json.get("http_code").toString().equals("413") && retryAttemptsLeft > 0) {
Amazing hint ! Thank you.
This will reduce the complexity by far.

2021-05-15 22:40 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/Request.java
> +    public void setRetryAttemptsLeft(int retryAttemptsLeft) {
I think protected should be possible in the case of keeping the call in the assembly.save().
(To maintain accessibility for the async assembly)

2021-05-16 11:06 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/Assembly.java
> +            request.setRetryAttemptsLeft(retryAttempts);
As it is not overwritten in AsyncAssembly it is covered by inheritance i would say. 
In case of handling this with the Transloadit class this should be no concern anyways

2021-05-16 11:08 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/Request.java
> +    public void setRetryAttemptsLeft(int retryAttemptsLeft) {
I think protected could be an alternative but this method could be discarded in case of alternatively handling this situation.

2021-05-16 12:09 UTC, cdr-chakotay commented
> Amazing work! I left a few comments. Also, would it be possible to add a unit test for this?

Maybe a "non-mock" test by using the rate-limit test account can be performed. I think it is an better idea to try out this in correspondence with the web API

2021-05-16 20:29 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Assembly.java
> +        this.retryAttempts = retryAttempts;
As mentioned on Slack, I think this option should only be in the Transloadit class :)

2021-05-16 20:37 UTC, Acconut commented
> Maybe a "non-mock" test by using the rate-limit test account can be performed. I think it is an better idea to try out this in correspondence with the web API

Not sure I agree here. Such an end-to-end test would only be possible if the developer has access to a special Transloadit account with a low rate limit. For worker at Transloadit this is not a problem but if an external contributor tries to run the test suite, they will have a hard time hitting the rate limit.

A typical unit test using a mocked response should be able to easily test the retry mechanism and also allows for fast debugging cycles if the test fails. Furthermore, we already have the test infrastructure for these mock tests but not for fully end-to-end tests.

Or am I missing something here?

2021-05-16 21:42 UTC, cdr-chakotay commented
> > Maybe a "non-mock" test by using the rate-limit test account can be performed. I think it is an better idea to try out this in correspondence with the web API
> 
> Not sure I agree here. Such an end-to-end test would only be possible if the developer has access to a special Transloadit account with a low rate limit. For worker at Transloadit this is not a problem but if an external contributor tries to run the test suite, they will have a hard time hitting the rate limit.
> 
> A typical unit test using a mocked response should be able to easily test the retry mechanism and also allows for fast debugging cycles if the test fails. Furthermore, we already have the test infrastructure for these mock tests but not for fully end-to-end tests.
> 
> Or am I missing something here?

No i think you are right. I'll give the mock test a try ASAP

2021-05-17 13:21 UTC, cdr-chakotay commented
> Amazing work! I left a few comments. Also, would it be possible to add a unit test for this?

Yes

2021-05-17 13:38 UTC, Acconut approved these changes
nice!

2021-05-17 13:44 UTC, merged