Prepared Release
transloadit/java-sdk pull request #88
Opened 2022-12-14 15:09 UTC by cdr-chakotay

Hey @Acconut, I thought about making the jump to 1.0.0 

I prepared everything and a little explanation in the changelog. Need a final testing and approval from your side.

Production tests and suggestions from your side are welcome :)

2022-12-19 13:40 UTC, Acconut requested changes

2022-12-19 13:40 UTC, Acconut commented on build.gradle
> -            email 'support@transloadit.com'
Maybe let's keep a developer entry with support@transloadit in there as well, next to you. It is a catch all mail, so it should be always reachable.

2022-12-19 13:40 UTC, Acconut commented on CHANGELOG.md
> +This version introduces some breaking changes and is Warning: This version includes breaking changes and some
It would be nice to have an explicit list of what the breaking changes are and how users need to change their code to be compatible with the new version. I have something like the Breaking Changes section from https://tus.io/blog/2022/08/03/tus-js-client-300.html in mind. Or are the changes too numerous and this would not be feasible?

2022-12-22 17:27 UTC, cdr-chakotay commented on build.gradle
> -            email 'support@transloadit.com'
Did as intended :)

2022-12-22 17:30 UTC, cdr-chakotay commented on CHANGELOG.md
> +This version introduces some breaking changes and is Warning: This version includes breaking changes and some
Well I thought I did that ?

How can I point it out better, that these ARE the breaking changes ?

2023-01-06 18:43 UTC, cdr-chakotay commented on CHANGELOG.md
> +This version introduces some breaking changes and is Warning: This version includes breaking changes and some
@Acconut

2023-01-16 11:20 UTC, Acconut commented on CHANGELOG.md
> +This version introduces some breaking changes and is Warning: This version includes breaking changes and some
Yes, you are stating that there are breaking changes and what new features have been added. But I am looking for a list of methods, classes, inferfaces etc. that have changed from the previous version in such a way that users of this library must adapt their code. Think of it as an upgrade guide: Which method calls must be replaced with what other methods to be able to upgrade to the latest version of the Java SDK? Does this make sense?

2023-01-16 21:54 UTC, cdr-chakotay commented
@Acconut revised the changelog. How is it about now.

2023-01-17 11:13 UTC, Acconut commented on CHANGELOG.md
> +This version introduces some breaking changes and is Warning: This version includes breaking changes and some
> This version introduces some breaking changes and is Warning: This version includes breaking changes and some experimental features, please keep that in mind when using it.

This does not read like a full sentence. Please correct it. Otherwise everything looks good!

2023-01-17 17:40 UTC, merged