Implement SSE
transloadit/java-sdk pull request #90
Opened 2023-10-19 20:16 UTC by cdr-chakotay

Implement Server Sent Events (SSE) as replacement for socket polling.

This is due to SSE preference from the Transloadit API.

2024-01-11 09:30 UTC, Acconut commented
Let me know if you need some more assistance here :)

2024-01-12 01:16 UTC, cdr-chakotay commented
> Let me know if you need some more assistance here :)

Hey @Acconut thank you for the reminder! I was occupied with other work in the meantime. I would like to continue on this soon. I let you know if I need anything :)

2024-09-09 10:59 UTC, Acconut requested changes
This PR is looking sharp! I have only a few comments and then we can get this on the road. Congrats on getting this so far 🎉

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Assembly.java
> +        final ConnectStrategy connectStrategy = ConnectStrategy.http(sseUpdateStreamUrl).connectTimeout(10, TimeUnit.MINUTES);
10 min is a long connection timeout. Maybe 30s is more appropriate? Or does the connect timeout also include the time while the updates are read from the SSE?

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Assembly.java
> +        final ErrorStrategy errorStrategy = ErrorStrategy.alwaysContinue();
What does this mean? Can you add a brief comment about `alwaysContinue`?

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/AssemblyListener.java
> +    void onAssemblyProgress(double combinedProgress, JSONObject progressPerOriginalFile);
Does every user of the Java SDK now have to update their listeners when they upgrade the Java SDK? If so, this would be a breaking change.

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +    public EventsourceRunnable(Transloadit transloadit, AssemblyResponse response, AssemblyListener assemblyListener, URI statusUri) {
`statusUri` is part of `AssemblyResponse`, isn't it? If so, can we get rid of one and avoid data duplication?

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    LocalOperationException e = new LocalOperationException("Unknown SSE message: " + data);
We shouldn't error out on unknown events. In the future, we might add new events and SDKs should not start failing then.

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    assemblyListener.onFileUploadFinished(fileName, payload);
I would prefer if just pass in `payload` since it already includes the name.

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    System.exit(1);
A library should not cause the process to exit.

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                        overallProgress = 0;
Can we make overallProgress `null` is this case to indicate that we don't know overall progress (versus it being 0)?

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    LocalOperationException e = new LocalOperationException("Unknown SSE message: " + data);
Same as above. We should not error out on unknown events.

2024-09-09 10:59 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    } else if (streamEvent instanceof CommentEvent) {
Since we don't use CommentEvent, StartedEvent and FaultEvents, can we just remove them here and reduce the LOC? I also don't think we will be used them soon.

2024-09-09 10:59 UTC, Acconut commented on src/test/resources/__files/sse_response_body
> +id: 2b7beaddf0a046e2ada603346f2cbee1
Can we give this file a `.txt` extension?

2024-09-09 10:59 UTC, Acconut commented on src/test/java/com/transloadit/sdk/AssemblyTest.java
>                  System.err.println("No Mockserver Response");
Is this log line still relevant? Can we remove it?

2024-09-09 10:59 UTC, Acconut commented on src/test/java/com/transloadit/sdk/AssemblyTest.java
> +                .respond(HttpResponse.response().withBody(sseBody));
I love this test setup! Thank you for implementing it this way!

2024-09-09 10:59 UTC, Acconut commented on src/test/java/com/transloadit/sdk/AssemblyTest.java
> +                emittedEvents.put("ASSEMBLY_RESULT_FINISHED", true);
Can you add assertions to the event argments here and in the other methods? Then we can be sure that the data from SSE is passed properly to the listener.

2024-09-11 20:15 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    LocalOperationException e = new LocalOperationException("Unknown SSE message: " + data);
What do you think about piping this as "onError" Event inside the assembly listener ?

2024-09-11 20:21 UTC, cdr-chakotay commented on src/test/java/com/transloadit/sdk/AssemblyTest.java
>                  System.err.println("No Mockserver Response");
Good catch! Will also remove the unused overloaded constructor

2024-09-11 20:22 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +    public EventsourceRunnable(Transloadit transloadit, AssemblyResponse response, AssemblyListener assemblyListener, URI statusUri) {
Good catch! Will also remove the unused overloaded constructor

2024-09-11 20:23 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    assemblyListener.onFileUploadFinished(fileName, payload);
Would be another breaking change, but we can include that one as well if you want. Do you?

2024-09-11 20:25 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    } else if (streamEvent instanceof CommentEvent) {
I'd like to keep them, also the started event is sent by the library itself :)

2024-09-11 20:30 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                        overallProgress = 0;
Well the Assembly Listener takes up a double value. `null`would provoke an Exception. We could just pass the raw Progress object, but this makes it harder for the user to consume. I can see both version being legitimate. I decided to do so in the past, however we can overhaul this. That's the same discussion as with the file name I would say ;)

2024-09-12 06:52 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    LocalOperationException e = new LocalOperationException("Unknown SSE message: " + data);
Unknown events are not an error and shouldn't be forwarded to the user. If SDKs error out on unknown events, we cannot add new ones in the future.

2024-09-12 06:53 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    assemblyListener.onFileUploadFinished(fileName, payload);
No, that's fine then. Let's reduce breaking changes if possible :)

2024-09-12 06:56 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                        overallProgress = 0;
Do I see it correctly that this PR introduces the onAssemblyProgress listener? If so, we now have the ability to shape its signature to best fit its current requirements as well as future extension. Therefore, I am in favor of just providing the entire progress object to the listener. Then the user also has access to new fields if we add them in the future.

2024-09-12 09:24 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                        overallProgress = 0;
Okay then let's do it that way :)

2024-11-25 21:58 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +                    LocalOperationException e = new LocalOperationException("Unknown SSE message: " + data);
Did resolve this

2024-11-25 21:59 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/AssemblyListener.java
> +    void onAssemblyProgress(double combinedProgress, JSONObject progressPerOriginalFile);
Interface is still there but has fewer parameters now.

2024-12-02 10:01 UTC, cdr-chakotay commented on src/test/java/com/transloadit/sdk/AssemblyTest.java
> +                emittedEvents.put("ASSEMBLY_RESULT_FINISHED", true);
Did that one as well :)

2024-12-03 11:28 UTC, Acconut requested changes
Thank you very much for the final updates! I have included a few suggestions to improve the documentation's spelling and some other minor comments. Other than that, this is good to go!

2024-12-03 11:28 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Assembly.java
> +     * @throws LocalOperationException - If the pause operation fails inside the upload runnable.
```suggestion
     * Pause parallel file uploads.
     *
     * @throws LocalOperationException - If the pause operation fails inside the upload runnable.
```

2024-12-03 11:28 UTC, Acconut commented on src/main/java/com/transloadit/sdk/Assembly.java
> +     * @throws LocalOperationException - If the resume operation fails inside the upload runnable.
```suggestion
     * Resume parallel file uploads.
     *
     * @throws LocalOperationException - If the resume operation fails inside the upload runnable.
```

2024-12-03 11:28 UTC, Acconut commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +public class EventsourceRunnable implements Runnable {
Is it necessary to make this class public? Can we make it package private? It's an implementation detail, so users don't need to be aware of it.

2024-12-03 11:28 UTC, Acconut commented on src/test/java/com/transloadit/sdk/AssemblyTest.java
> +        put("ASSEMBLY_ERROR", new Object[]{false, 0});
Do we need the boolean and the counter? Could we just use the counter and assert the number of calls to the specific listener event? Then we could turn this into a `Map<String, int>` and get rid of the ambiguous `Object`.

2024-12-03 12:32 UTC, Acconut commented on examples/src/main/java/com/transloadit/examples/KotlinExample.kt
> +                    // .put("font","Helvetica") You can put Helvetica here in order to test the error handling
If you say it did work, do you mean that the Assembly completed without error? If so, the comment would be incorrect and should be updated or removed.

I also question the comments purpose in this file. The example should be easy to read and understand for customers. This comment would rather confuse me as a customer because I don't understand how it can help test error handling. Hence, I am suggesting removing it altogether.

2024-12-03 17:10 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/Assembly.java
> +                public void onFileUploadFinished(JSONObject uploadInformation) {
We have to do anyway as we will have the assembly status and therefore the listener interface is altered, which you need to implement in Java. So i just made it equally styled for all of the interfaces as the user need to touch it anyway.

2024-12-03 17:11 UTC, cdr-chakotay commented on examples/src/main/java/com/transloadit/examples/KotlinExample.kt
> +                    // .put("font","Helvetica") You can put Helvetica here in order to test the error handling
Maybe I also recall it not correctly, I will double-check for sure :)

2024-12-03 17:22 UTC, cdr-chakotay commented on src/main/java/com/transloadit/sdk/EventsourceRunnable.java
> +public class EventsourceRunnable implements Runnable {
I guess so, good catch

2024-12-05 08:29 UTC, Acconut approved these changes
As far as I can tell, all feedback got addressed and the tests are passing. So this PR is good to go 🚀 Congrats on finishing this incredible work 🏅

2024-12-05 08:30 UTC, Acconut commented on examples/src/main/java/com/transloadit/examples/KotlinExample.kt
> +                    // .put("font","Helvetica") You can put Helvetica here in order to test the error handling
You removed the comment in a later commit, so this resolved now.

2024-12-05 12:21 UTC, cdr-chakotay commented
> As far as I can tell, all feedback got addressed and the tests are passing. So this PR is good to go 🚀 Congrats on finishing this incredible work 🏅

Thanks! I will do another double-check and merge it then :)

2024-12-06 12:46 UTC, merged

2024-12-06 14:33 UTC, kvz commented
Congrats on landing this 💪💪

we should have a column in the sdks table in the docs: supports SSE :)